//FUNCTIONS
import { ADDPACKAGE } from "../PACKAGES/ADDPACKAGE/AddPackage.js";
import { ADDSTORAGE } from "../PACKAGES/ADDSTORAGE/AddStorage.js";
import { CLEAR } from "../PACKAGES/CLEARCOMPONENTS/ClearComponents.js";
import { DELETESTORAGE } from "../PACKAGES/DELETESTORAGE/DeleteStorage.js";
import { DISPLAYDATA } from "../PACKAGES/DISPLAYDATA/DisplayData.js";
import { GETPACKAGE } from "../PACKAGES/GETPACKAGE/GetPackage.js";
import { GETSTORAGE } from "../PACKAGES/GETSTORAGE/GetStorage.js";
import { OPERATINGSYSTEM } from "../PACKAGES/OPERATIONCHECKER/OperationChecker.js";
import { POSTPACKAGE } from "../PACKAGES/POSTPACKAGE/PostPage.js";
import { REMOVESTORAGE } from "../PACKAGES/REMOVESTORAGE/RemoveStorage.js";
import { SHUFFLEDATA } from "../PACKAGES/SHUFFLEDATA/ShuffleData.js";
import { STYLED } from "../PACKAGES/STYLECOMPONENTS/StyleComponents.js";
import { ZOOMEFFECT } from "../PACKAGES/ZOOMEFFECT/ZoomEffect.js";

//API
const COUNTRIESAPI=`../APIS/Countries.json`;

//ASSETS
const WHITEICONSAPI=`../ASSETS/ICONS/WHITE/`;
const BLACKICONSAPI=`../ASSETS/ICONS/BLACK/`;
const SOUNDSAPI=`../ASSETS/SOUNDS/`;
const VIDEOAPI=`../ASSETS/VIDEOS/`;
const IMAGESAPI=`../ASSETS/IMAGES/`;







export{COUNTRIESAPI,WHITEICONSAPI,BLACKICONSAPI,SOUNDSAPI,VIDEOAPI,IMAGESAPI,ADDPACKAGE,ADDSTORAGE,CLEAR,DELETESTORAGE,DISPLAYDATA,GETPACKAGE,GETSTORAGE,OPERATINGSYSTEM,POSTPACKAGE,REMOVESTORAGE,SHUFFLEDATA,STYLED,ZOOMEFFECT}